## Knative Serving Kustomization
#
# This kustomization configures Knative Serving from the DigitalOcean Marketplace repo to:
#   1. Install the net-certmanager component (`patches/net-certmanager-install.yaml`)
#   2. Configures Knative Serving to use the `kn-letsencrypt-http01-issuer` cluster issuer (`patches/certmanager-config.yaml`)
#   3. Configures Knative Serving to use a custom domain (`patches/domain-config.yaml`)
#   4. Configures Knative Serving for auto TLS (`patches/network-config.yaml`)
##

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - https://github.com/knative/serving/releases/download/knative-v1.12.3/serving-crds.yaml
  # - resources/knative-serving-crd.yaml # changing to the cr that worked 
  - resources/knative-serving-CR.yaml
  - resources/kn-cluster-issuer.yaml # creates the `kn-letsencrypt-http01-issuer` cluster issuer
patchesStrategicMerge:
  # - target:
  #     group: apps
  #     version: v1
  #     kind: Deployment
  #     name: cert-manager
  #     namespace: cert-manager
  #   path: patches/net-certmanager-install.yaml


  - patches/net-certmanager-install.yaml # MANULLY APPLIED
  - patches/certmanager-config.yaml
  - patches/domain-config.yaml
  - patches/network-config.yaml
