apiVersion: v1
kind: Service
metadata:
  name: my-knative-service
spec:
  selector:
    serving.knative.dev/service: my-knative-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
